=== fann2mass/JD2019-03-11/src/by/it/eslaikouskaya/jd02_07/Boritorg.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT site (catalogs, aboutus, shortinfo, properties)>
        <!ELEMENT catalogs (catalog)+>
        <!ELEMENT catalog (name, elements)>
        <!ELEMENT elements (element)+>
        <!ELEMENT element (description, content)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT content (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT aboutus (about)>
        <!ELEMENT about (#PCDATA)>
        <!ELEMENT shortinfo (city, address, notation, managerstel)>
        <!ELEMENT managerstel (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT notation (#PCDATA)>
        <!ELEMENT properties (property)+>
        <!ELEMENT property (mark, info)>
        <!ELEMENT mark (#PCDATA)>
        <!ELEMENT info (#PCDATA)>

=== fann2mass/JD2019-03-11/src/by/it/eslaikouskaya/jd02_07/Boritorg+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE site SYSTEM "Boritorg.dtd" >
<site>
    <catalogs>
        <catalog>
            <name>Сантехника</name>
            <elements>
                <element>
                    <description>Системы трубопровода из полипропилена</description>
                    <content>Трубы серые армированные
                        Угольники
                        Муфты
                        Американки
                        Тройники
                        Опоры
                        Краны
                        Фильтры из полипропилена
                    </content>
                </element>
                <element>
                    <description>Трубные стальные заготовки</description>
                    <content>Сгоны
                        Резьбы
                        Контргайки
                        Муфты
                        Бочонки
                        Угольники
                        Тройники
                        Отводы
                        Черные и оцинкованные
                    </content>
                </element>
                <element>
                    <description>Запорная арматура</description>
                    <content>Краны шаровые муфтовые
                        Фланцевые задвижки
                        Вентили
                        Фильтры
                        Обратные клапаны и фланцы к ним
                    </content>
                </element>
                <element>
                    <description>Элементы креплений</description>
                    <content>Болты
                        Гайки
                        Шайбы
                        Шпильки
                        Хомуты ремонтные
                        Хомуты для крепления труб
                    </content>
                </element>
                <element>
                    <description>Радиаторы и системы отопления</description>
                    <content>Радиаторы алюминевые
                        Радиаторы биметаллические
                        Радиаторы чугунные
                        Кронштейны
                        Клапаны для регулировки
                        Монтажные комплекты
                    </content>
                </element>
                <element>
                    <description>Трубы полиэтиленовые</description>
                    <content>Трубы ПЭ от 25-63 мм
                        Муфты
                        Тройники
                        Угольники
                        Заглушки и другие фитинги к ним
                    </content>
                </element>
                <element>
                    <description>Трубы асбестноцементные</description>
                    <content>Трубы безнапорные 110х3.95м, 160х3.95м
                        Трубы напорные 200х5м
                    </content>
                </element>
                <element>
                    <description>Сантехническое оборудование</description>
                    <content>Унитазы
                        Умывальники
                        Поддоны душевые
                        Биде
                        Писсуары
                        Смесители
                        Гибкие подводки и прочее
                    </content>
                </element>
                <element>
                    <description>Уплотнительные материалы и прочее</description>
                    <content>Паронитовые прокладки
                        Техпластина каболка
                        Лен сантехнический
                        Шнур асбестовый
                        Асбокартон
                        Электроды
                    </content>
                </element>
                <element>
                    <description>Трубы канализационные ПВХ и НПВХ</description>
                    <content>Трубы для наружней и внутренней канализации, фасонные части к ним
                        Трапы
                        Люки
                    </content>
                </element>
            </elements>
        </catalog>
        <catalog>
            <name>Металлопрокат</name>
            <elements>
                <element>
                    <description>Уголок</description>
                    <content>Уголок 25-100 мм</content>
                </element>
                <element>
                    <description>Арматура рифленая</description>
                    <content>Арматура рифленая 6 — 20 мм</content>
                </element>
                <element>
                    <description>Трубы круглые</description>
                    <content>Труба ВГП 15-50 мм
                        Труба электросварная 57-325 мм
                        Труба оцинкованная 15-108 мм
                    </content>
                </element>
                <element>
                    <description>Полоса</description>
                    <content>Полоса 25х4 и 40х4</content>
                </element>
                <element>
                    <description>Трубы профильные</description>
                    <content>Трубы профильные от 15х15 до 100х100 мм</content>
                </element>
                <element>
                    <description>Листы</description>
                    <content>Лист г/к 2 — 10 мм
                        Лист х/к 0.8 — 1.5 мм
                        Лист оцинкованный
                        Лист с полимерным покрытием
                        Лист рифленый
                        Лист ПВЛ
                    </content>
                </element>
                <element>
                    <description>Проволока вязальная</description>
                    <content>Проволока вязальная 1.2 — 5 мм</content>
                </element>
                <element>
                    <description>Швеллер</description>
                    <content>Швеллер 8 — 20 мм</content>
                </element>
                <element>
                    <description>Круг гладкий</description>
                    <content>Круг 6 -12 мм</content>
                </element>
                <element>
                    <description>Квадрат</description>
                    <content>Квадрат 10х10 мм</content>
                </element>
            </elements>
        </catalog>
        <catalog>
            <name>Стройматериалы</name>
            <elements>
                <element>
                    <description>Блоки газосиликатные</description>
                    <content>100х290х600
                        200х290х600
                        250х300х600
                        250х400х600
                        Перемычки газосиликатные
                    </content>
                </element>
                <element>
                    <description>Кирпич</description>
                    <content>Кирпич силикатный
                        Кирпич керамический
                        Кирпич цветной гиперпрессованный
                        Кирпич лицевой
                        Кирпич огнеупорный
                    </content>
                </element>
                <element>
                    <description>Поликарбонат</description>
                    <content>Поликарбонат 4-10мм 2100х6000
                        Прозрачный
                        Цветной
                        Профиль торцевой
                        Профиль пристенный
                        Профиль соединительный
                    </content>
                </element>
                <element>
                    <description>Гипсокартон и комплектующие</description>
                    <content>Гипсокартон стеновой
                        Гипсокартон потолочный
                        Гипсокартон влагостойкий
                        Профиль
                        Подвесы
                        Крабы и др
                    </content>
                </element>
                <element>
                    <description>Цемент и строительные смеси</description>
                    <content>Цемент
                        Штукатурка
                        Шпатлевка
                        Клей
                        Расстворы
                        Стяжка и др
                    </content>
                </element>
                <element>
                    <description>Плиты стружечные</description>
                    <content>ДСП
                        ДВП
                        плита ОСБ 9-18 мм
                        ФАНЕРА
                        ЦСП
                    </content>
                </element>
                <element>
                    <description>Сетка</description>
                    <content>3мм 0.5х2 (50х50)
                        3мм 1х2(100х100)
                        3мм 1х2(150х150)
                        4мм 0.5х2 (50х50)
                        4мм 1х2(100х100)
                        5мм 1х2(100х100)
                        Сетка рабица
                        Сетка ССШ
                    </content>
                </element>
                <element>
                    <description>Кольца колодцев</description>
                    <content>Кольцо ж/б 1.0 -2.0 м
                        Плита перекрытия
                        Днище колодца
                        Доборные кольца 0.7м
                        Люки чугунные
                        Люки полимерные
                    </content>
                </element>
                <element>
                    <description>Плитка тротуарная, бордюры</description>
                    <content>Плитка серая красная
                        Кирпичик 60,80мм
                        Старый город
                        Черепашка
                        Калифорния
                        Квадрат ажурный
                        Борт тротуарный и дорожный
                    </content>
                </element>
                <element>
                    <description>Теплоизоляция</description>
