=== fann2mass/JD2019-03-11/src/by/it/narushevich/jd02_07/users.dtd
<?xml version="1.0" encoding="UTF-8" ?>
    <!ELEMENT users (user)+>
    <!ELEMENT user (login, password, email, location, collection)>
    <!ELEMENT login (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT collection (teaTag)+>
    <!ELEMENT teaTag (trademark, originCountry, purchaseCountry,
            material, width, height, corners, inCollectionSince, exchange)>
    <!ELEMENT trademark (#PCDATA)>
    <!ELEMENT originCountry (#PCDATA)>
    <!ELEMENT purchaseCountry (#PCDATA)>
    <!ELEMENT material (#PCDATA)>
    <!ELEMENT width (#PCDATA)>
    <!ATTLIST width
                currency PCDATA #REQUIRED>
    <!ELEMENT height (#PCDATA)>
    <!ATTLIST height
                currency PCDATA #REQUIRED>
    <!ELEMENT corners (#PCDATA)>
    <!ELEMENT inCollectionSince (#PCDATA)>
    <!ELEMENT exchange (#PCDATA)>

=== fann2mass/JD2019-03-11/src/by/it/narushevich/jd02_07/users+dtd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "users.dtd" >
<users>
    <user>
        <login>Masha05</login>
        <password>qwerty</password>
        <email>masha.dot@gmail.com</email>
        <location>Belarus, Minsk</location>
        <collection>
            <teaTag>
                <trademark>Lipton</trademark>
                <originCountry>India</originCountry>
                <purchaseCountry>Belarus</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">26</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2005</inCollectionSince>
                <exchange>yes</exchange>
            </teaTag>
            <teaTag>
                <trademark>Golden Bowl</trademark>
                <originCountry>Sri-Lanka</originCountry>
                <purchaseCountry>Belarus</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">26</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>1999</inCollectionSince>
                <exchange>yes</exchange>
            </teaTag>
        </collection>
    </user>
    <user>
        <login>Robby98</login>
        <password>njimko</password>
        <email>mir.tea@gmail.com</email>
        <location>France, Paris</location>
        <collection>
            <teaTag>
                <trademark>Maitre de The</trademark>
                <originCountry>China</originCountry>
                <purchaseCountry>France</purchaseCountry>
                <material>paper</material>
                <width currency="mm">23</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2012</inCollectionSince>
                <exchange>yes</exchange>
            </teaTag>
            <teaTag>
                <trademark>Darling</trademark>
                <originCountry>Sri-Lanka</originCountry>
                <purchaseCountry>England</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">23</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2001</inCollectionSince>
                <exchange>yes</exchange>
            </teaTag>
        </collection>
    </user>
</users>
