=== fann2mass/JD2019-03-11/src/by/it/khlystunova/jd02_09/clients.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.khlystunova.it.by/"
        xmlns:my="http://beans.jd02_09.khlystunova.it.by/"
        elementFormDefault="qualified">
    <element name="clients">
        <complexType>
            <sequence>
                <element
                        name="client"
                        type="my:Client"
                        maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Client">
        <sequence>
            <element name="name" type="string" />
            <element name="surname" type="string" />
            <element name="dateOfBirthday" type="string" />
            <element name="buys" type="my:Buys" />
        </sequence>
    </complexType>

    <complexType name="Buys">
        <sequence>
            <element name="buy"
                     type="my:Buy"
                     maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="Buy">
        <all>
            <element name="description" type="string" />
            <element name="firm" type="string" />
            <element name="price" type="my:Price" />
            <element name="size" type="string" />
            <element name="color" type="string" />
        </all>
    </complexType>
    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== fann2mass/JD2019-03-11/src/by/it/khlystunova/jd02_09/clients+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns="http://beans.jd02_09.khlystunova.it.by/"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://beans.jd02_09.khlystunova.it.by/  clients.xsd">
    <client>
        <name>Lisa</name>
        <surname>Khlystunova</surname>
        <dateOfBirthday>21.03.1997</dateOfBirthday>
        <buys>
            <buy>
                <description>Кожаные туфли</description>
                <firm>ecco</firm>
                <price currency="EUR">200</price>
                <size>39</size>
                <color>black</color>
            </buy>
            <buy>
                <description>Лонслив</description>
                <firm>H(&amp;)M</firm>
                <price currency="EUR">3400</price>
                <size>S</size>
                <color>white</color>
            </buy>
            <buy>
                <description>Джинсы</description>
                <firm>Levi(&apos;)s</firm>
                <price currency="USD">4500</price>
                <size>S</size>
                <color>white</color>
            </buy>
        </buys>
    </client>
    <client>
        <name>Nastia</name>
        <surname>Tolmachova</surname>
        <dateOfBirthday>21.02.1998</dateOfBirthday>
        <buys>
            <buy>
                <description>Пальто</description>
                <firm>Milan</firm>
                <price currency="USD">77777</price>
                <size>S</size>
                <color>red</color>
            </buy>
            <buy>
                <description>Майка</description>
                <firm>adidas</firm>
                <price currency="USD">77777</price>
                <size>S</size>
                <color>blue</color>
            </buy>
            <buy>
                <description>Юбка</description>
                <firm>Morgan</firm>
                <price currency="USD">77777</price>
                <size>S</size>
                <color>blue</color>
            </buy>
        </buys>
    </client>
</clients>
