=== fann2mass/JD2019-03-11/src/by/it/bildziuh/jd02_07/users.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT users (admin)(user)+>
        <!ELEMENT admin (login,password,email)>
        <!ELEMENT user (login,password,email,mods)>
        <!ELEMENT login (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT mods (mod)+>
        <!ELEMENT mod (game,group,name,description,size, link)>
        <!ELEMENT game (#PCDATA)>
        <!ELEMENT group (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT link (#PCDATA)>

=== fann2mass/JD2019-03-11/src/by/it/bildziuh/jd02_07/users+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "users.dtd" >
<users>
    <admin>
        <login>admin</login>
        <password>admin</password>
        <email>admin@admin.admin</email>
    </admin>
    <user>
        <login>Vasya</login>
        <password>qwerty</password>
        <email>vasya@gmail.com</email>
        <mods>
            <mod>
                <game>Skyrim</game>
                <group>UI</group>
                <name>better UI</name>
                <description>Улучшить интерфейс бесплатно, без смс и регистрации</description>
                <size>42</size>
                <link>gdisk</link>
            </mod>
            <mod>
                <game>Witcher 3</game>
                <group>Animations</group>
                <name>Killing spree</name>
                <description>Новые анимации добивания оппонента</description>
                <size>84</size>
                <link>gdisk</link>
            </mod>
        </mods>
    </user>
    <user>
        <login>Petya</login>
        <password>asdfgh</password>
        <email>petya@tut.by</email>
        <mods>
            <mod>
                <game>World of warcraft</game>
                <group>UI</group>
                <name>Deadly Boss Mods</name>
                <description>Отображение дополнительных панелей информации</description>
                <size>480</size>
                <link>gdisk</link>
            </mod>
        </mods>
    </user>
    <user>
        <login>Vanya</login>
        <password>zxcvb</password>
        <email>vanya@mail.sru</email>
        <mods>
            <mod>
                <game>World of warcraft</game>
                <group>UI</group>
                <name>DBM Legion</name>
                <description>расширение DBM для контента Legion. Необходимо иметь установленный Deadly Boss Mods
                </description>
                <size>120</size>
                <link>gdisk</link>
            </mod>
        </mods>
    </user>
</users>
