<?xml version="1.0" encoding="UTF-8"  standalone="yes" ?>
<!-- начало описания DTD для этой XML (все внутри т.к. standalone="yes") -->
<!DOCTYPE students [
<!ELEMENT students (student)+>
<!ELEMENT student (name, nickname, telephone, address)>
<!ATTLIST student
        login ID #REQUIRED
        course CDATA #REQUIRED
        >
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT address (country, city, street)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
]> <!-- конец описания DTD для этой XML -->
<students>
    <student login="IvanovMitarAlex7" course='it.jd.02'>
        <name>Ivanov Alexander</name>
        <nickname>&quot;M&amp;M&apos;s&quot;</nickname>
        <telephone>4586954</telephone>
        <address>
            <country>Belarus</country>
            <city>Minsk</city>
            <street>Lenina 3</street>
        </address>
    </student>

    <student login="zPav16" course='it.jd.02'>
        <name>Zimin Pavel</name>
        <nickname>&lt;Daemond&gt;</nickname>
        <telephone>2569854</telephone>
        <address>
            <country>Belarus</country>
            <city>Grodno</city>
            <street>Gikalo 21</street>
        </address>
    </student>
</students>