=== fann2mass/JD2019-03-11/src/by/it/akhmelev/jd02_07/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02_09.akhmelev.it.by/"
        xmlns:my="http://jd02_09.akhmelev.it.by/"
        elementFormDefault="qualified">
<element name="users">
  <complexType>
    <sequence>
      <element
              name="user"
              type="my:TypeOfUser"
              minOccurs="1"
              maxOccurs="unbounded" />
    </sequence>
  </complexType>
</element>

<complexType name="TypeOfUser">
  <sequence>
    <element name="login" type="string" />
    <element name="password" type="string" />
    <element name="email" type="string" />
    <element name="ads" type="my:TypeOfAds" />
  </sequence>
</complexType>


<complexType name="TypeOfAds">
  <sequence>
    <element name="ad"
             type="my:TypeOfAd"
             minOccurs="1"
             maxOccurs="unbounded" />
  </sequence>
</complexType>

<complexType name="TypeOfAd">
  <all>
    <element name="description" type="string" />
    <element name="address" type="string" />
    <element name="floor" type="integer" />
    <element name="floors" type="positiveInteger" />
    <element name="rooms" type="positiveInteger" />
    <element name="price" type="my:TypeOfPrice" />
  </all>
</complexType>

<complexType name="TypeOfPrice">
  <simpleContent>
    <extension base="double">
      <attribute name="currency" type="string"/>
    </extension>
  </simpleContent>
</complexType>


</schema>

=== fann2mass/JD2019-03-11/out/production/JD2019-03-11/by/it/akhmelev/jd02_07/users+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="http://jd02_09.akhmelev.it.by/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://jd02_09.akhmelev.it.by/ users.xsd">
  <user>
    <login>Vasya</login>
    <password>qwerty</password>
    <email>vasya@gmail.com</email>
    <ads>
      <ad>
        <description>Самая лучшая квартира в Минске</description>
        <address>г. Минск, ул. Ленина 42, кв 42</address>
        <floor>3</floor>
        <floors>5</floors>
        <rooms>3</rooms>
        <price currency="USD">99999</price>
      </ad>
      <ad>
        <description>Самая лучшая квартира в Пинске</description>
        <address>г. Пинск, ул. Гагарина 12, кв 32</address>
        <floor>2</floor>
        <floors>6</floors>
        <rooms>2</rooms>
        <price currency="USD">77777</price>
      </ad>
    </ads>
  </user>
  <user>
    <login>Petya</login>
    <password>asdfgh</password>
    <email>petya@tut.by</email>
    <ads>
      <ad>
        <description>Маленькая квартирка в Минске</description>
        <address>г. Минск, ул. Гикало 2, кв 2</address>
        <floor>1</floor>
        <floors>5</floors>
        <rooms>1</rooms>
        <price currency="BYN">88888.8</price>
      </ad>
    </ads>
  </user>
</users>
