=== fann2mass/JD2019-03-11/src/by/it/narushevich/jd02_09/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.narushevich.it.by/"
        xmlns:my="http://beans.jd02_09.narushevich.it.by/"
        elementFormDefault="qualified">
    <element name="users">
        <complexType>
            <sequence>
                <element
                        name="user"
                        type="my:User"
                        minOccurs="1"
                        maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="User">
        <sequence>
            <element name="login" type="string" />
            <element name="password" type="string" />
            <element name="email" type="string" />
            <element name="location" type="string" />
            <element name="collection" type="my:Collection" />
        </sequence>
    </complexType>


    <complexType name="Collection">
        <sequence>
            <element name="teaTag"
                     type="my:TeaTag"
                     minOccurs="1"
                     maxOccurs="unbounded" />
        </sequence>
    </complexType>

    <complexType name="TeaTag">
        <all>
            <element name="trademark" type="string" />
            <element name="originCountry" type="string" />
            <element name="purchaseCountry" type="string" />
            <element name="material" type="string" />
            <element name="width" type="my:Width" />
            <element name="height" type="my:Height" />
            <element name="corners" type="string" />
            <element name="inCollectionSince" type="positiveInteger" />
            <element name="exchange" type="boolean" />
        </all>
    </complexType>

    <complexType name="Width">
        <simpleContent>
            <extension base="double">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>
    <complexType name="Height">
        <simpleContent>
            <extension base="double">
                <attribute name="currency" type="string"/>
            </extension>
        </simpleContent>
    </complexType>


</schema>

=== fann2mass/JD2019-03-11/src/by/it/narushevich/jd02_09/users+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns="http://beans.jd02_09.narushevich.it.by/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://beans.jd02_09.narushevich.it.by/ users.xsd">
    <user>
        <login>Masha05</login>
        <password>qwerty</password>
        <email>masha.dot@gmail.com</email>
        <location>Belarus, Minsk</location>
        <collection>
            <teaTag>
                <trademark>Lipton</trademark>
                <originCountry>India</originCountry>
                <purchaseCountry>Belarus</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">26</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2005</inCollectionSince>
                <exchange>true</exchange>
            </teaTag>
            <teaTag>
                <trademark>Golden Bowl</trademark>
                <originCountry>Sri-Lanka</originCountry>
                <purchaseCountry>Belarus</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">26</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>1999</inCollectionSince>
                <exchange>true</exchange>
            </teaTag>
        </collection>
    </user>
    <user>
        <login>Robby98</login>
        <password>njimko</password>
        <email>mir.tea@gmail.com</email>
        <location>France, Paris</location>
        <collection>
            <teaTag>
                <trademark>Maitre de The</trademark>
                <originCountry>China</originCountry>
                <purchaseCountry>France</purchaseCountry>
                <material>paper</material>
                <width currency="mm">23</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2012</inCollectionSince>
                <exchange>true</exchange>
            </teaTag>
            <teaTag>
                <trademark>Darling</trademark>
                <originCountry>Sri-Lanka</originCountry>
                <purchaseCountry>England</purchaseCountry>
                <material>cardboard</material>
                <width currency="mm">23</width>
                <height currency="mm">28</height>
                <corners>cut off</corners>
                <inCollectionSince>2001</inCollectionSince>
                <exchange>true</exchange>
            </teaTag>
        </collection>
    </user>
</users>
