=== fann2mass/JD2019-03-11/src/by/it/bolotko/jd02_09/parkings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://beans.jd02_09.bolotko.it.by/"
        xmlns:my="http://beans.jd02_09.bolotko.it.by/"
        elementFormDefault="qualified">
<element name="parkings">
  <complexType>
    <sequence>
      <element name="parking"
               type="my:Parking"
               maxOccurs="unbounded" />
    </sequence>
  </complexType>
</element>

  <complexType name="Parking">
    <sequence>
      <element name="first_name" type="string" />
      <element name="last_name" type="string" />
      <element name="year_of_birth" type="string" />
      <element name="drivers_license_number" type="string" />
      <element name="category" type="string" />
      <element name="cars" type="my:Cars" />
      <element name="prices" type="my:Prices" />
    </sequence>
  </complexType>

  <complexType name="Cars">
    <sequence>
      <element name="car"
               type="my:Car"
               maxOccurs="unbounded" />

    </sequence>
  </complexType>

  <complexType name="Car">
    <sequence>
      <element name="car_model" type="string" />
      <element name="car_type" type="string" />
      <element name="numbers" type="string" />
    </sequence>
  </complexType>

  <complexType name="Prices">
    <sequence>
      <element name="price"
               type="my:Price"
               maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="Price">
    <sequence>
      <element name="number_of_cars" type="string" />
      <element name="total_price" type="my:Total_price" />
    </sequence>
  </complexType>

  <complexType name="Total_price">
    <simpleContent>
      <extension base="double">
        <attribute name="currency" type="string" />
      </extension>
    </simpleContent>
  </complexType>
</schema>

=== fann2mass/JD2019-03-11/src/by/it/bolotko/jd02_09/parkings+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<parkings xmlns="http://beans.jd02_09.bolotko.it.by/"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://beans.jd02_09.bolotko.it.by/ parkings.xsd">
    <parking>
        <first_name>Michail</first_name>
        <last_name>Sidorov</last_name>
        <year_of_birth>12.04.1994</year_of_birth>
        <drivers_license_number>2156812</drivers_license_number>
        <category>A,B</category>
        <cars>
            <car>
                <car_model>Audi</car_model>
                <car_type>Passenger car</car_type>
                <numbers>8354CB-1</numbers>
            </car>
            <car>
                <car_model>BMW</car_model>
                <car_type>Jeep</car_type>
                <numbers>8359CB-1</numbers>
            </car>
        </cars>
        <prices>
            <price>
                <number_of_cars>2</number_of_cars>
                <total_price currency="BYN">120</total_price>
            </price>
        </prices>
    </parking>
    <parking>
        <first_name>Aleksandr</first_name>
        <last_name>Potapov</last_name>
        <year_of_birth>24.12.1984</year_of_birth>
        <drivers_license_number>2105361</drivers_license_number>
        <category>B</category>
        <cars>
            <car>
                <car_model>Lada</car_model>
                <car_type>Passenger car</car_type>
                <numbers>6122AA-2</numbers>
            </car>
        </cars>
        <prices>
            <price>
                <number_of_cars>1</number_of_cars>
                <total_price currency="BYN">60</total_price>
            </price>
        </prices>
    </parking>

</parkings>
